[package]
name = "codex-helper-tui"
version = "0.11.0"
edition = "2024"

[dependencies]
codex-helper-core = { path = "../core" }
anyhow = "1.0.100"
ratatui = "0.30.0"
crossterm = { version = "0.29.0", features = ["event-stream"] }
unicode-width = "0.2"
tokio = { version = "1.48.0", features = ["macros", "rt-multi-thread", "signal", "fs"] }
futures-util = "0.3.31"
reqwest = { version = "0.13.1", features = ["json", "stream"] }
serde_json = "1.0.145"
